map_type: costmap

obstacle_range: 0.95
raytrace_range: 0.8

transform_tolerance: 0.20

inflation_radius: 2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
